### ISSUE TITLE
Wrong statistics reported by JTL compared to that from Locust UI

### ISSUE THREAD

**Issue by puran157** [ludeknovy/jtl-reporter#277]
**Describe the bug**
On running a test in locust, I see huge difference in numbers of locust with those in JTL reporter. For ex:- requests, error count are 10 times higher in locust UI when compared to JTL reporter.
Following script is used to stream data to JTL while test is running
https://github.com/ludeknovy/jtl-reporter/blob/main/scripts/jtl_listener_service.py

**To Reproduce**
Started seeing this from past couple of weeks

**Expected behavior**
The numbers from locust UI and JTL should match

**Screenshots**

**Additional context**
You can get the logs by running: `docker logs <service_name>`

**Did JtlReporter make you happay in any way?**
Yes

**Comment by puran157** [comment]
Locust version `locust 2.20.0 from /usr/lib/python3.10/site-packages/locust (python 3.10.11)`

**Comment by ludeknovy** [comment]
Hi @puran157 
could you also try and compare when uploading the jtl file (not using the listener service). Does it give you the same result?

> Started seeing this from past couple of weeks

Did you upgrade anything recently? JtlReporter or locust?

**Comment by puran157** [comment]
root->fire:53 Uncaught exception in event handler:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/locust/event.py", line 47, in fire
    handler(**kwargs)
  File "/root/demo-project/jtl_listner.py", line 86, in _worker_report
    self.csv_results += data["csv"]
KeyError: 'csv'

When I try uploading jtl way.

Jtl reporter is latest and locust is on version mentioned above

**Comment by ludeknovy** [comment]
You might want to upload that file manually via UI, just to see if there are any differences as well. The thing is I dont think I've changed anything related to processing lately, that should change the outcome.

**Comment by puran157** [comment]
> You might want to upload that file manually via UI, just to see if there are any differences as well. The thing is I dont think I've changed anything related to processing lately, that should change the outcome.

Yup, I checked the csv and JTL is reporting what's present in csv perfectly fine. Its just the csv has wrong statistics. Perhaps a dictionary change from locust recently?

**Comment by ludeknovy** [comment]
Yes, it could be a change from locust side. But for that I will need more time to investigate.

**Comment by puran157** [comment]
My bad, found the issue, JTL listener service wasn't initialized on worker nodes hence the missing numbers.
